name: histogram-tutorial
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - numba
  - numpy
  - pandas
  - hist >=2.4
  - mypy >=0.900
  - histoprint
  - uhi
  - mplhep
  - pip >=18
  - uncertainties
  - pip:
    - uproot-browser >=0.2.0
